<?php
/**
 * Created by PhpStorm.
 * User: shady
 * Date: 5/13/2018
 * Time: 6:09 AM
 */

class WfMenuWidget extends WfWidget {

	public function __construct() {
		parent::__construct(
			'wf_events_menu_widget',
			__( 'Menu Widget', 'wfevents' ),
			array( 'description' => __( 'This widget includes a facebook like box on your blog', 'wfevents' ), )
		);
	}

	function form( $instance ) {
		//return parent::form( $instance ); // TODO: Change the autogenerated stub
		$title = isset( $instance['title'] ) ? $instance['title'] : '';
		WfHtml::render('menu_widget', array('model'=>$this,'title'=>$title));
	}

	function update( $new_instance, $old_instance ) {
		//return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
		$instance = array();
		$instance['title']         = ( ! empty( $new_instance['title'] ) ) ? sanitize_text_field( $new_instance['title'] ) : '';
		return $instance;
	}

	function widget( $args, $instance ) {
		$title = apply_filters( 'widget_title', $instance['title'] );

		echo $args['before_widget'];
		WfHtml::render('menu_widget_layout',array('title'=>$title));
	//	parent::widget( $args, $instance ); // TODO: Change the autogenerated stub
	}

	static function add_widget( $name ) {
		//add_action('widgets_init',function($name){
		//	register_widget($name);
		//});
	}


}